// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmmqisypzauehxmdhnwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtbXFpc3lwemF1ZWh4bWRobndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Nzc0NDksImV4cCI6MjA3MjM1MzQ0OX0.XOZvV5dOMGUC-QvTW4JeinaHLG2k1pm0DV709ZXerls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});